"""KenzyClient unit tests — runnable without Home Assistant installed
(the api module only needs aiohttp)."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from custom_components.kenzy.api import _sign  # noqa: E402


def test_signature_matches_kenzy_wire_format():
    """Fixed vector generated by kenzy.serviceauth.sign_service_request
    (token='test-fleet-token', ts=1700000000, GET /assist). If this breaks,
    the reimplementation drifted from the kenzy wire format — fix HERE, the
    server side is the authority."""
    import time
    from unittest.mock import patch

    with patch.object(time, "time", return_value=1700000000):
        header = _sign("test-fleet-token", "GET", "/assist")
    assert header == (
        "KENZY-HMAC ts=1700000000, "
        "sig=eb3e55be3ad06bc15573b6b3e5807a6706a3db9e92a5fae6ad2fbc44c5a99e68"
    )
